# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TelloGestureControl' do
  platform :ios, '14.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TelloGestureControl
  pod 'CocoaAsyncSocket'
  pod 'paper-onboarding'

end

target 'TelloGestureControl WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TelloGestureControl WatchKit App

end

target 'TelloGestureControl WatchKit Extension' do
  platform :watchos, '7.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TelloGestureControl WatchKit Extension

end
